modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "appwrapper"
version = "${version}"
displayName = "AppWrapper"
authors = "Kall"
description = '''
A Minecraft mod
'''
#logoFile = ""
